services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.piquel-resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.piquel-resolver.acme.email=piquel@piquel.fr"
      - "--certificatesresolvers.piquel-resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # - mode: host
      #   protocol: tcp
      #   published: 80
      #   target: 80
      # - mode: host
      #   protocol: tcp
      #   published: 443
      #  :target: 443
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: piquel-fr
      POSTGRES_USER: ${DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "${PGADMIN_PORT}:80"
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  # satisfactory:
  #   image: wolveix/satisfactory-server:latest
  #   container_name: satisfactory
  #   ports:
  #       - '7777:7777/udp'
  #       - '7777:7777/tcp'
  #   volumes:
  #       - '${DATA_PATH}/satisfactory:/config'
  #   environment:
  #       - MAXPLAYERS=4
  #       - PGID=1000
  #       - PUID=1000
  #       - ROOTLESS=false
  #       - STEAMBETA=false

volumes:
  #data: ${DATA_PATH}
  postgres:
  pgadmin:
  letsencrypt:
