services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: piquel-fr
      POSTGRES_USER: ${DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 60s
      timeout: 5s
      retries: 5
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "${PGADMIN_PORT}:80"
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  # satisfactory:
  #   image: wolveix/satisfactory-server:latest
  #   container_name: satisfactory
  #   ports:
  #       - '7777:7777/udp'
  #       - '7777:7777/tcp'
  #   volumes:
  #       - '${DATA_PATH}/satisfactory:/config'
  #   environment:
  #       - MAXPLAYERS=4
  #       - PGID=1000
  #       - PUID=1000
  #       - ROOTLESS=false
  #       - STEAMBETA=false

volumes:
  #data: ${DATA_PATH}
  postgres:
  pgadmin:
