services:
  traefik:
    image: traefik:v3.3
    command:
      # Basic setup
      - "--api=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=piquel-network"

      # Setup certs
      - "--certificatesresolvers.piquel-resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.piquel-resolver.acme.email=${VPS_USER_EMAIL}"
      - "--certificatesresolvers.piquel-resolver.acme.storage=/letsencrypt/acme.json"

      # piquel-fr entrypoints
      - "--entrypoints.piquel-https.address=:443"
      - "--entrypoints.piquel-https.http.tls.certresolver=piquel-resolver"

      - "--entrypoints.piquel-http.address=:80"
      - "--entrypoints.piquel-http.http.redirections.entrypoint.to=piquel-https"
      - "--entrypoints.piquel-http.http.redirections.entrypoint.scheme=https"

      # PostgreSQL entrypoint
      - "--entrypoints.postgres.address=:5432"
      - "--entrypoints.postgres.http.tls.certresolver=piquel-resolver"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - mode: host
        protocol: tcp
        published: 5432
        target: 5432
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=piquel-https"
      - "traefik.http.routers.traefik.tls.certresolver=piquel-resolver"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - piquel-network
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: piquel-fr
      POSTGRES_USER: ${DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`${DB_HOST}`)"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.routers.postgres.tls.certresolver=piquel-resolver"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - piquel-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_HOST}`)"
      - "traefik.http.routers.pgadmin.entrypoints=piquel-https"
      - "traefik.http.routers.pgadmin.tls.certresolver=piquel-resolver"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - piquel-network
  # satisfactory:
  #   image: wolveix/satisfactory-server:latest
  #   container_name: satisfactory
  #   ports:
  #       - '7777:7777/udp'
  #       - '7777:7777/tcp'
  #   volumes:
  #       - '${DATA_PATH}/satisfactory:/config'
  #   environment:
  #       - MAXPLAYERS=4
  #       - PGID=1000
  #       - PUID=1000
  #       - ROOTLESS=false
  #       - STEAMBETA=false

volumes:
  #data: ${DATA_PATH}
  postgres:
  pgadmin:
  letsencrypt:

networks:
  piquel-network:
    driver: overlay
    attachable: true
    name: piquel-network
