name: Deploy
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "TRAEFIK_HOST=${{ vars.TRAEFIK_HOST }}" >> ./.env
          echo "TRAEFIK_AUTH=${{ secrets.TRAEFIK_AUTH }}" >> ./.env

          echo "DB_HOST=${{ vars.DB_HOST }}" >> ./.env
          echo "DB_ADMIN_USER=${{ secrets.DB_ADMIN_USER }}" >> ./.env
          echo "DB_ADMIN_PASSWORD=${{ secrets.DB_ADMIN_PASSWORD }}" >> ./.env

          echo "PGADMIN_HOST=${{ vars.PGADMIN_HOST }}" >> ./.env
          echo "PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}" >> ./.env
          echo "PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}" >> ./.env

          echo "VPS_USER_EMAIL=${{ secrets.VPS_USER_EMAIL }}" >> ./.env

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: piquel-vps
          file: docker-stack.yml
          host: piquel.fr
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./.env
